# Nazwa aplikacji
spring.application.name=marketingCampaign-manager

# Konfiguracja bazy danych H2
spring.datasource.url=jdbc:h2:mem:campaigndb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Konfiguracja Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# konsola H2 (pozwala na zobaczenie bazy pod adresem /h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console